services:
  app:
    build: .
    container_name: omni-osint-query
    env_file:
      - .env
    environment:
      - ARANGODB_HOST=http://arangodb:8529
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - arangodb
      - redis
    command: uvicorn omni_osint_query.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3s
      timeout: 9s
      retries: 3

  arangodb:
    image: arangodb/arangodb:3.12
    command: arangod --experimental-vector-index
    container_name: osint-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
    ports:
      - "8529:8529"

  redis:
    image: redis:7-alpine
    container_name: osint-redis
    ports:
      - "6379:6379"
